name: RG25
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - pip
  - pip:
      - cv2_enumerate_cameras
      - pupil-apriltags
      - pyserial
      - nicegui
      - asyncio
      - pyee
